#!/bin/sh
# mcli c show --active | grep vpn >/dev/null && echo "<span foreground='#81a1c1' background='#2e3440' size='x-large'></span><span background='#81a1c1'> <span foreground='#2e3440' size='large' rise='1pt'></span> </span><span background='#81a1c1' foreground='#2e3440' size='x-large'></span>" || echo "<span foreground='#81a1c1' background='#2e3440' size='x-large'></span><span background='#81a1c1'> <span foreground='#bf616a' size='large' rise='1pt'></span> </span><span background='#81a1c1' foreground='#2e3440' size='x-large'></span>"


t1=$(cat /sys/devices/platform/coretemp.0/hwmon/hwmon2/temp1_input)
t2=$(cat /sys/devices/platform/coretemp.0/hwmon/hwmon2/temp2_input)
t3=$(cat /sys/devices/platform/coretemp.0/hwmon/hwmon2/temp3_input)
tmps="${t1%000}-${t2%000}-${t3%000}"


echo "<span foreground='#81a1c1' background='#2e3440' size='x-large'></span><span background='#81a1c1'><span foreground='#2e3440' size='small' rise='1pt'> $tmps</span> </span><span background='#81a1c1' foreground='#2e3440' size='x-large'></span>"
