#!/bin/bash
# Alsamixer
# vol=$(awk -F"[][]" '/Left:/ { print $2 }' <(amixer sget Master | grep "\[on\]") | sed 's/%//')
# Pulseaudio
vol=$(pacmd dump-volumes | awk 'NR==1{print $8}' | sed 's/\%//')

# pulsemixer --get-mute | grep 0 > /dev/null && echo "<span foreground='#81A1C1' size='large'></span> <span size='small' rise='2pt'>$(pulsemixer --get-volume | awk '{print $1}')%</span>" || echo "<span foreground='#bf616a' size='large'>ﱝ</span>"
if [ "$vol" -gt "0" ]; then
  echo "<span foreground='#81A1C1' size='large'></span> <span size='small' rise='2pt'>$vol%</span>" 
else
  echo "<span foreground='#bf616a' size='large'>ﱝ</span>"
fi
